app:
  name: "point-of-sales-api"
  port: 8080

db:
  host: "localhost"
  port: "5432"
  username: "root"
  password: "root"
  database: "pos"
  sslmode: "disable"
  max_idle_conns: 10
  max_open_conns: 25
  max_lifetime: 60
  max_idle_time: 60
